"""add admin

Revision ID: 2cb6656aac64
Revises: 0e49d81ac0c3
Create Date: 2016-09-04 19:33:55.344000

"""

# revision identifiers, used by Alembic.
revision = '2cb6656aac64'
down_revision = '0e49d81ac0c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    ### end Alembic commands ###
